deploy:
	  aws cloudformation deploy --template-file template.yaml --stack-name jh-authentication --capabilities CAPABILITY_IAM

delete:
	  aws cloudformation delete-stack --stack-name jh-authentication
